<?php

return [
    /*
    |--------------------------------------------------------------------------
    | Minimum distinct matched terms required to flag a letter
    |--------------------------------------------------------------------------
    | Keep this low for child safety.
    */
    'minimum_distinct_terms_to_flag' => 1,

    /*
    |--------------------------------------------------------------------------
    | Suspicious / dirty / unsafe terms
    |--------------------------------------------------------------------------
    | Keep everything lowercase.
    | This is only a first-layer keyword scan, not full moderation.
    | You can later move this into weighted categories if needed.
    */
    'terms' => [
        // Basic profanity
        'damn',
        'hell',
        'crap',
        'shit',
        'bullshit',
        'ass',
        'asshole',
        'bastard',
        'bitch',
        'son of a bitch',
        'motherfucker',
        'fucker',
        'fuck',
        'fucking',
        'fucked',
        'wtf',
        'piss',
        'dick',
        'jerk',
        'jerkoff',
        'slut',
        'whore',

        // Bullying / harassment
        'idiot',
        'stupid',
        'dumb',
        'ugly',
        'loser',
        'moron',
        'freak',
        'weirdo',
        'trash',
        'pathetic',
        'useless',
        'worthless',
        'disgusting',
        'creep',
        'psycho',
        'crazy',
        'fat',
        'fatty',
        'lame',
        'shut up',
        'go away',
        'nobody likes you',
        'everyone hates you',
        'i hate you',
        'hate you',
        'you are stupid',
        'you are dumb',
        'you are ugly',
        'you are weird',
        'you are gross',
        'you are disgusting',
        'you are worthless',
        'you are a loser',
        'you are pathetic',
        'you are trash',

        // Threat / violence
        'kill',
        'kill you',
        'i will kill you',
        'i will hurt you',
        'hurt you',
        'beat you',
        'beat you up',
        'punch you',
        'slap you',
        'stab you',
        'cut you',
        'attack you',
        'destroy you',
        'i will find you',
        'you will regret it',
        'watch your back',
        'i hate you',
        'die',
        'go die',
        'drop dead',
        'choke',
        'smash your face',
        'break your neck',
        'shoot you',
        'burn you',
        'burn your house',
        'i will get you',
        'revenge',
        'threat',
        'blackmail',

        // Sexual / explicit
        'sex',
        'sexy',
        'sexual',
        'naked',
        'nude',
        'nudity',
        'topless',
        'bottomless',
        'undress',
        'take off your clothes',
        'strip',
        'make out',
        'kiss me',
        'kiss your lips',
        'touch me',
        'touch your body',
        'touch yourself',
        'private part',
        'private parts',
        'body part',
        'breast',
        'boob',
        'boobs',
        'nipple',
        'nipples',
        'butt',
        'booty',
        'penis',
        'vagina',
        'genital',
        'genitals',
        'underwear pic',
        'nude pic',
        'nude pics',
        'send nudes',
        'send me a pic',
        'send me your pic',
        'send me a photo of your body',
        'show me your body',
        'show me your chest',
        'show me your legs',
        'show me your private parts',
        'show your body',
        'hot body',
        'turn me on',
        'horny',
        'aroused',
        'porn',
        'porno',
        'pornography',
        'xxx',
        'adult video',
        'adult content',
        'explicit',
        'fetish',
        'seduce',
        'bed with me',
        'sleep with me',
        'have sex',
        'do sex',
        'sexual photo',
        'dirty pic',
        'dirty picture',
        'dirty video',
        'naked photo',
        'naked picture',

        // Grooming / child-safety risk phrases
        'dont tell your parents',
        'do not tell your parents',
        'dont tell anyone',
        'do not tell anyone',
        'keep this secret',
        'keep it secret',
        'our secret',
        'just between us',
        'only between us',
        'nobody needs to know',
        'no one needs to know',
        'delete this message',
        'hide this message',
        'secret chat',
        'private chat',
        'private message me',
        'talk in private',
        'message me privately',
        'come alone',
        'meet alone',
        'meet me alone',
        'meet in secret',
        'meet me secretly',
        'send your address',
        'where do you live',
        'home address',
        'school address',
        'what school do you go to',
        'send your location',
        'share your location',
        'send me your number',
        'what is your phone number',
        'video call me',
        'call me alone',
        'go to your room',
        'close the door',
        'show me in private',
        'you are mature for your age',
        'you are so mature',
        'you can trust me',
        'trust only me',
        'i wont tell anyone',
        'i will keep your secret',
        'be my secret friend',
        'special secret',
        'special relationship',
        'secret relationship',

        // Coercion / manipulation
        'if you love me',
        'prove you love me',
        'prove it',
        'if you care about me',
        'you must do it',
        'do it now',
        'or else',
        'i will expose you',
        'i will tell everyone',
        'i will leak it',
        'send it now',
        'you owe me',
        'dont say no',
        'you have to obey',
        'be obedient',
        'listen to me only',
        'you belong to me',
        'be mine',
        'my property',
        'do what i say',

        // Self-harm / severe distress risk
        'kill myself',
        'i want to die',
        'i will die',
        'suicide',
        'self harm',
        'cut myself',
        'hurt myself',

        // Other unsafe / unethical
        'steal',
        'stole',
        'cheat',
        'cheating',
        'lie to your parents',
        'lie to your mom',
        'lie to your dad',
        'run away',
        'skip school',
        'break the rules',
        'break into',
        'hack',
        'hacking',
        'drugs',
        'weed',
        'cocaine',
        'alcohol',
        'beer',
        'vodka',
        'smoke',
        'smoking',
        'vape',
        'vaping',
    ],
];